/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystemproject;

import java.awt.Toolkit;

/**
 *
 * @author maxra
 */
public class adminLogin extends javax.swing.JFrame {

    /**
     * Creates new form adminLogin
     */
    public adminLogin() {
        initComponents();
        errorMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPasswordInput = new javax.swing.JPasswordField();
        hoemButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        adminLoginButton = new javax.swing.JButton();
        errorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminPasswordInput.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adminPasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPasswordInputActionPerformed(evt);
            }
        });
        getContentPane().add(adminPasswordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 192, 725, 58));

        hoemButton.setText("Home");
        hoemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoemButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hoemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 401, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("enter the admin password:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 119, 809, -1));

        adminLoginButton.setText("submit");
        adminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(adminLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 268, -1, -1));

        errorMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        errorMessage.setText("INCORRECT PASSWORD");
        getContentPane().add(errorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 300, 437, 75));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminPasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPasswordInputActionPerformed
       
    }//GEN-LAST:event_adminPasswordInputActionPerformed

    private void adminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginButtonActionPerformed
 String pword = new String(adminPasswordInput.getPassword());
        String password = "admin";
        if(password.equals(pword)){
             adminOptions start = new adminOptions();
                Toolkit tk = Toolkit.getDefaultToolkit();
                int width = (int) tk.getScreenSize().getWidth();
                int height = (int) tk.getScreenSize().getHeight();

                start.setSize(width, height);
                start.setVisible(true);
        }else{
            errorMessage.setVisible(true);
        }
        
    }//GEN-LAST:event_adminLoginButtonActionPerformed

    private void hoemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoemButtonActionPerformed
      usefulMethods u = new usefulMethods();
      u.homeButton();
    }//GEN-LAST:event_hoemButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLoginButton;
    private javax.swing.JPasswordField adminPasswordInput;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JButton hoemButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
