/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystemproject;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashSet;

/**
 *
 * @author maxra
 */
public class cleaningView extends javax.swing.JFrame {

    
    public cleaningView() {
        initComponents();
        usefulMethods u = new usefulMethods();
        String b = "";
        ArrayList<String> inOrder = new ArrayList<>();
        
        ArrayList<Integer> bookingHours2 = new ArrayList<Integer>();
        for (int i = 0; i < u.bookings.size(); i++) {
         
            bookingHours2.add(u.toHours(u.bookings.get(i).getMonth(), u.bookings.get(i).getDay() + "", u.bookings.get(i).getTime()));
        }
        Collections.sort(bookingHours2);

        
        LinkedHashSet<Integer> hashSet = new LinkedHashSet<Integer>(bookingHours2);
        ArrayList<Integer> bookingHoursWithNoDuplicates = new ArrayList<>(hashSet);
        
       
   
        for (int k = 0; k < bookingHoursWithNoDuplicates.size(); k++) {
            for (int l = 0; l < u.bookings.size(); l++) {
                if (bookingHoursWithNoDuplicates.get(k) == u.toHours(u.bookings.get(l).getMonth(), u.bookings.get(l).getDay() + "", u.bookings.get(l).getTime())) {
                    String cleaningTime = "";
                    if (u.bookings.get(l).getTime().equals("09:00")) {
                        cleaningTime = "10:00";
                    } else {
                        cleaningTime = u.bookings.get(l).getTime().substring(0, 1) + (Integer.parseInt(u.bookings.get(l).getTime().substring(1, 2)) + 1) + u.bookings.get(l).getTime().substring(2, 5);
                    }

                    inOrder.add("please set out "+ u.bookings.get(l).getResources()+" for the meeting commencing at "+ u.bookings.get(l).getTime()+" in room "+ u.bookings.get(l).getRoomNo()+"\nplease clean Room Number: " + u.bookings.get(l).getRoomNo() + "       " + u.bookings.get(l).getMonth() + " / " + u.bookings.get(l).getDay() + " / " + cleaningTime + "\n");

                }

            }
        }

        for (int k = 0; k < inOrder.size(); k++) {
            
            System.out.println(inOrder.get(k));
            b = b + inOrder.get(k) + "\n";
        }
        jTextArea1.setText(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        monthSelection = new javax.swing.JComboBox<>();
        daySelection = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 70, 1230, 570));

        jButton1.setText("home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("cleaning schedule");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 250, 40));

        monthSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "january", "febuary", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december" }));
        monthSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthSelectionActionPerformed(evt);
            }
        });
        getContentPane().add(monthSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, -1, -1));

        daySelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(daySelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, 90, -1));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("after you've finished cleaning please remember to set out resources in the next booked room");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        usefulMethods u = new usefulMethods();
        u.homeButton();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void monthSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthSelectionActionPerformed

    }//GEN-LAST:event_monthSelectionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        usefulMethods u = new usefulMethods();
        String b = "";
        for (int i = 0; i < u.bookings.size(); i++) {
            if (u.bookings.get(i).getMonth().equals(monthSelection.getSelectedItem().toString()) && (u.bookings.get(i).getDay() + "").equals(daySelection.getSelectedItem().toString())) {
               

                String cleaningTime = "";
                if (u.bookings.get(i).getTime().equals("09:00")) {
                    cleaningTime = "10:00";
                } else {
                    cleaningTime = u.bookings.get(i).getTime().substring(0, 1) + (Integer.parseInt(u.bookings.get(i).getTime().substring(1, 2)) + 1) + u.bookings.get(i).getTime().substring(2, 5);
                }

                //String cleaningTime = u.bookings.get(i).getTime().substring(0,1)+(Integer.parseInt(u.bookings.get(i).getTime().substring(1,2))+1)+u.bookings.get(i).getTime().substring(2, 5);
                b = b + ("\nplease set out "+ u.bookings.get(i).getResources()+" for the meeting commencing at "+ u.bookings.get(i).getTime()+" in room "+ u.bookings.get(i).getRoomNo()+"\nplease clean Room Number: " + u.bookings.get(i).getRoomNo() + "       " + u.bookings.get(i).getMonth() + " / " + u.bookings.get(i).getDay() + " / " + cleaningTime + "\n");

            }

        }
        jTextArea1.setText(b);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cleaningView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cleaningView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cleaningView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cleaningView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cleaningView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> daySelection;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> monthSelection;
    // End of variables declaration//GEN-END:variables
}
