/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystemproject;

import java.awt.Toolkit;
import javax.swing.JComboBox;

/**
 *
 * @author maxra
 */
public class newBooking extends javax.swing.JFrame {

    /**
     * Creates new form newBooking
     */
    public newBooking() {
        initComponents();
        wheelchairErrorMessage.setVisible(false);
        passwordErrorMessage.setVisible(false);
        bookingSizeErrorMessage.setVisible(false);
        emailErrorMessage.setVisible(false);
        bookingErrorMessage.setVisible(false);
        alreadyBookingErrorMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        wheelchair = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        monthSelection = new javax.swing.JComboBox<>();
        daySelection = new javax.swing.JComboBox<>();
        timeSelection = new javax.swing.JComboBox<>();
        pens = new javax.swing.JCheckBox();
        paper = new javax.swing.JCheckBox();
        pencils = new javax.swing.JCheckBox();
        projector = new javax.swing.JCheckBox();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        refreshmentsField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        bookingSizeField = new javax.swing.JLabel();
        bookingSize = new javax.swing.JTextField();
        rTimeSelection = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        confirmPasswordField = new javax.swing.JTextField();
        passwordErrorMessage = new javax.swing.JLabel();
        bookingSizeErrorMessage = new javax.swing.JLabel();
        wheelchairErrorMessage = new javax.swing.JLabel();
        emailErrorMessage = new javax.swing.JLabel();
        bookingErrorMessage = new javax.swing.JLabel();
        alreadyBookingErrorMessage = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 179, 104, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 216, 104, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 253, 104, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("confirm password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 297, 136, -1));

        wheelchair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wheelchairActionPerformed(evt);
            }
        });
        getContentPane().add(wheelchair, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 331, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("wheelchair access");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 331, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("refreshments");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 374, 104, -1));

        monthSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "january", "febuary", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december" }));
        monthSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthSelectionActionPerformed(evt);
            }
        });
        getContentPane().add(monthSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 449, -1, -1));

        daySelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(daySelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 449, 90, -1));

        timeSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "10:30", "12:00", "13:30", "15:00", "16:30", "18:00" }));
        timeSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSelectionActionPerformed(evt);
            }
        });
        getContentPane().add(timeSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 449, -1, -1));

        pens.setText("pens");
        getContentPane().add(pens, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 532, -1, -1));

        paper.setText("paper");
        paper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperActionPerformed(evt);
            }
        });
        getContentPane().add(paper, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 562, -1, -1));

        pencils.setText("pencils");
        getContentPane().add(pencils, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 592, -1, -1));

        projector.setText("projector");
        getContentPane().add(projector, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 622, -1, -1));
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 176, 282, -1));
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 210, 282, -1));
        getContentPane().add(refreshmentsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 282, -1));

        jLabel7.setText("which do you require:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 507, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("New Booking");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 96, -1, -1));

        submitButton.setText("submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, -1, -1));

        bookingSizeField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bookingSizeField.setText("how many people would you like to book for");
        getContentPane().add(bookingSizeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 412, -1, -1));

        bookingSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingSizeActionPerformed(evt);
            }
        });
        getContentPane().add(bookingSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 282, -1));

        rTimeSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "start", "10 minutes", "20 minutes", "30 minutes", "40 minutes", "50 minutes" }));
        getContentPane().add(rTimeSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(982, 374, -1, -1));

        jLabel9.setText("how far in would you like them?");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 377, -1, -1));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 250, 282, -1));
        getContentPane().add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 294, 282, -1));

        passwordErrorMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        passwordErrorMessage.setText("passwords do not match");
        getContentPane().add(passwordErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, -1, -1));

        bookingSizeErrorMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bookingSizeErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        bookingSizeErrorMessage.setText("sorry the maximum booking size is 50");
        getContentPane().add(bookingSizeErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, -1, -1));

        wheelchairErrorMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wheelchairErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        wheelchairErrorMessage.setText("maximum capacity is 15 with wheelchair access");
        getContentPane().add(wheelchairErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, -1, -1));

        emailErrorMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        emailErrorMessage.setText("invalid email address");
        getContentPane().add(emailErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, -1, -1));

        bookingErrorMessage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bookingErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        bookingErrorMessage.setText("sorry this has been booked");
        getContentPane().add(bookingErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 340, 30));

        alreadyBookingErrorMessage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        alreadyBookingErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        alreadyBookingErrorMessage.setText("you already have a booking on this day");
        getContentPane().add(alreadyBookingErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 470, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 51, 255));
        jLabel10.setText("(please include notes if you have more specific requirements or allergies)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 340, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wheelchairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheelchairActionPerformed

    }//GEN-LAST:event_wheelchairActionPerformed

    private void monthSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthSelectionActionPerformed

    }//GEN-LAST:event_monthSelectionActionPerformed

    private void timeSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeSelectionActionPerformed

    private void paperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paperActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        usefulMethods u = new usefulMethods();
        String wc = "no wheelchair";
        if (wheelchair.isSelected()) {
            wc = "wheelchair";
        }
        String resources = "";
        if (pens.isSelected()) {
            resources = resources + " pens";
        }
        if (pencils.isSelected()) {
            resources = resources + " pencils";
        }
        if (projector.isSelected()) {
            resources = resources + " projector";
        }
        if (paper.isSelected()) {
            resources = resources + " paper";
        }
        int room = u.suggestedRoom(Integer.parseInt(bookingSize.getText()),wc);
        if (passwordField.getText().equals(confirmPasswordField.getText()) && Integer.parseInt(bookingSize.getText()) <= 50 && ((wc.equals("wheelchair") && Integer.parseInt(bookingSize.getText()) <= 15) || wc.equals("no wheelchair")) && emailField.getText().contains("@") && emailField.getText().contains(".")&&u.availablity(monthSelection.getSelectedItem().toString(), daySelection.getSelectedItem().toString(), timeSelection.getSelectedItem().toString(),u.suggestedRoom(Integer.parseInt(bookingSize.getText().toString()), wc))==true&&u.alreadyGotBooking(monthSelection.getSelectedItem().toString(), daySelection.getSelectedItem().toString(), timeSelection.getSelectedItem().toString(),emailField.getText())==true) {
            bookingSlot b = new bookingSlot(nameField.getText(), emailField.getText(), passwordField.getText(), room, wc, refreshmentsField.getText(), rTimeSelection.getSelectedItem().toString(), monthSelection.getSelectedItem().toString(), Integer.parseInt(daySelection.getSelectedItem().toString()), timeSelection.getSelectedItem().toString(), resources);
            u.bookings.add(b);
            System.out.println(u.bookings);
            u.write();
            startingMenu start = new startingMenu();
            Toolkit tk = Toolkit.getDefaultToolkit();
            int width = (int) tk.getScreenSize().getWidth();
            int height = (int) tk.getScreenSize().getHeight();

            start.setSize(width, height);
            start.setVisible(true);
            this.dispose();
        } else {
            if (!passwordField.getText().equals(confirmPasswordField.getText())) {
                passwordErrorMessage.setVisible(true);
            } 
            if (Integer.parseInt(bookingSize.getText()) > 50) {
                bookingSizeErrorMessage.setVisible(true);
            } 
            if (wc.equals("wheelchair") && Integer.parseInt(bookingSize.getText()) > 15) {
                wheelchairErrorMessage.setVisible(true);
            } 
            if (!emailField.getText().contains("@") || !emailField.getText().contains(".")) {
                emailErrorMessage.setVisible(true);
            }
            if (u.availablity(monthSelection.getSelectedItem().toString(), daySelection.getSelectedItem().toString(), timeSelection.getSelectedItem().toString(),u.suggestedRoom(Integer.parseInt(bookingSize.getText().toString()), wc))==false){
                bookingErrorMessage.setVisible(true);
            }
            if (u.alreadyGotBooking(monthSelection.getSelectedItem().toString(), daySelection.getSelectedItem().toString(), timeSelection.getSelectedItem().toString(),emailField.getText())==false){
                alreadyBookingErrorMessage.setVisible(true);
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void bookingSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingSizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alreadyBookingErrorMessage;
    private javax.swing.JLabel bookingErrorMessage;
    private javax.swing.JTextField bookingSize;
    private javax.swing.JLabel bookingSizeErrorMessage;
    private javax.swing.JLabel bookingSizeField;
    private javax.swing.JTextField confirmPasswordField;
    private javax.swing.JComboBox<String> daySelection;
    private javax.swing.JLabel emailErrorMessage;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> monthSelection;
    private javax.swing.JTextField nameField;
    private javax.swing.JCheckBox paper;
    private javax.swing.JLabel passwordErrorMessage;
    private javax.swing.JTextField passwordField;
    private javax.swing.JCheckBox pencils;
    private javax.swing.JCheckBox pens;
    private javax.swing.JCheckBox projector;
    private javax.swing.JComboBox<String> rTimeSelection;
    private javax.swing.JTextField refreshmentsField;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox<String> timeSelection;
    private javax.swing.JCheckBox wheelchair;
    private javax.swing.JLabel wheelchairErrorMessage;
    // End of variables declaration//GEN-END:variables
}
