/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingsystemproject;

/**
 *
 * @author maxra
 */
public class userLogin extends javax.swing.JFrame {


 
    /**
     * Creates new form userLogin
     */
    public userLogin() {
        initComponents();
        bookingView.setVisible(false);
        jScrollPane1.setVisible(false);
        jLabel4.setVisible(false);
         deleteBookings.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        usernameInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingView = new javax.swing.JTextArea();
        deleteBookings = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Sign in");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, -1, -1));

        passwordInput.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        getContentPane().add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 302, -1));

        usernameInput.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 302, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("email address");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        loginButton.setText("login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, -1, -1));

        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        bookingView.setColumns(20);
        bookingView.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        bookingView.setRows(5);
        jScrollPane1.setViewportView(bookingView);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 1360, 450));

        deleteBookings.setText("delete my bookings");
        deleteBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookingsActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Your bookings");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
     usefulMethods u = new usefulMethods();
     if(u.checkDetails(passwordInput.getPassword(), usernameInput.getText())==true){
         jScrollPane1.setVisible(true);
         bookingView.setVisible(true);
         jLabel4.setVisible(true);
         deleteBookings.setVisible(true);
         jLabel1.setVisible(false);
         jLabel2.setVisible(false);
         jLabel3.setVisible(false);
         loginButton.setVisible(false);
         passwordInput.setVisible(false);
         usernameInput.setVisible(false);
     String bookingOutput = "";
     String pass = new String (passwordInput.getPassword());
     for(int i =0;i<u.bookings.size();i++){
         
         if (u.bookings.get(i).getEmail().equals(usernameInput.getText()) && u.bookings.get(i).getPassword().equals(pass)){
             bookingOutput = bookingOutput +"\nName: "+ u.bookings.get(i).getName()+"    Room number: "+u.bookings.get(i).getRoomNo()+"     appointment: "+u.bookings.get(i).getMonth()+" / "+u.bookings.get(i).getDay()+" / "+u.bookings.get(i).getTime()+"     refreshments: "+u.bookings.get(i).getRefreshments();
           //  bookingOutput = bookingOutput + u.bookings.get(i)+"\n";
             bookingView.setText(bookingOutput);
         }
     }}
    }//GEN-LAST:event_loginButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        usefulMethods u = new usefulMethods();
        u.homeButton();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookingsActionPerformed
        usefulMethods u = new usefulMethods();
        String pass = new String (passwordInput.getPassword());
        for(int i =0;i<u.bookings.size();i++){
            if (u.bookings.get(i).getEmail().equals(usernameInput.getText()) && u.bookings.get(i).getPassword().equals(pass)){
                u.bookings.remove(i);
            }
        }
        u.write();
    }//GEN-LAST:event_deleteBookingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bookingView;
    private javax.swing.JButton deleteBookings;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
